[package]
name = "docread"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
docx-rs = "0.4.17"
glob = "0.3.1"
rayon = "1.10.0"
regex = "1.11.1"
serde_json = "1.0.133"
