name: GNU/Linux

on:
  release:
    types: [created]


env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf false

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl

    - name: Run tests
      run: cargo test --verbose
    
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Tar x86_64 binary
      run: tar -czvf docread-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release docread

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 docread-gnu-linux-x86_64.tar.gz > docread-gnu-linux-x86_64.tar.gz.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["docread-gnu-linux-x86_64.tar.gz",  "docread-gnu-linux-x86_64.tar.gz.sha256"]'