name: GNU/Linux and Windows Build, Test, and Release

on:
  release:
    types: [created]


env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf false

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Run tests
      run: cargo test --verbose
    
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu
    
    - name: Tar x86_64 binary
      run: tar -czvf docread-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release docread

    - name: Zip windows binary
      run: zip -j docread-windows.zip target/x86_64-pc-windows-gnu/release/docread.exe
    
    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 docread-gnu-linux-x86_64.tar.gz > docread-gnu-linux-x86_64.tar.gz.sha256
        shasum -a 256 textpod-windows.zip > docread-windows.zip.sha256
  
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["docread-gnu-linux-x86_64.tar.gz", "docread-windows.zip",  "docread-gnu-linux-x86_64.tar.gz.sha256", "docread-windows.zip.sha256"]'